name:                hframes
version:             0.1.0.0
github:              "n-kishaloy/hframes"
license:             MIT
author:              "Kishaloy Neogi"
maintainer:          "nkishaloy@yahoo.com"
copyright:           "2021 Kishaloy Neogi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/n-kishaloy/hframes#readme>

dependencies: 
- base >= 4.7 && < 5

library: 
  exposed-modules: DataFrame
  source-dirs: src
  dependencies: 
  - text
  - vector
  - approx
  - time
  - hashable
  - containers
  - unordered-containers
  - lens

executables: 
  hframes-exe: 
    main:                Main.hs
    source-dirs:         app
    ghc-options: 
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: 
    - hframes
    - text
    - vector
    - approx
    - time
    - hashable
    - containers
    - unordered-containers
    - lens
    
tests:
  hframes-test: 
    main:                Spec.hs
    source-dirs:         test
    ghc-options: 
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: 
    - hframes
    - text
    - vector
    - approx
    - time
    - hashable
    - containers
    - unordered-containers
    - lens
